export const INITIAL_SERVICES = [
  // Infrastructure
  {
    id: 1,
    title: 'cAdivisor',
    category: 'Infrastructure',
    url: 'cadvisor.internal.novitech.dev',
    status: 'online',
    ssl: true,
    description: 'Container resource usage and performance analysis tool',
    tags: ['monitoring'],
    createdAt: Date.now(),
  },
  {
    id: 2,
    title: 'Grafana',
    category: 'Infrastructure',
    url: 'grafana.internal.novitech.dev',
    status: 'online',
    ssl: true,
    description: 'Analytics and monitoring dashboards',
    tags: ['monitoring', 'critical'],
    createdAt: Date.now() - 100000,
  },
  {
    id: 3,
    title: 'Nginx Proxy Manager',
    category: 'Infrastructure',
    url: 'nginx.internal.novitech.dev',
    status: 'online',
    ssl: true,
    description: 'Reverse proxy management UI',
    tags: ['critical', 'internal'],
    createdAt: Date.now() - 200000,
  },
  {
    id: 4,
    title: 'Portainer',
    category: 'Infrastructure',
    url: 'portainer.internal.novitech.dev',
    status: 'online',
    ssl: true,
    description: 'Docker container management',
    tags: ['critical', 'internal'],
    createdAt: Date.now() - 300000,
  },
  {
    id: 5,
    title: 'Prometheus',
    category: 'Infrastructure',
    url: 'prometheus.internal.novitech.dev',
    status: 'online',
    ssl: true,
    description: 'Metrics collection and alerting',
    tags: ['monitoring', 'critical'],
    createdAt: Date.now() - 400000,
  },
  {
    id: 6,
    title: 'Vault',
    category: 'Infrastructure',
    url: 'vault.internal.novitech.dev',
    status: 'online',
    ssl: true,
    description: 'Secrets and encryption management',
    tags: ['critical', 'internal'],
    createdAt: Date.now() - 500000,
  },

  // Development
  {
    id: 7,
    title: 'ChatApp API',
    category: 'Dev',
    url: 'chatapp-api.novitech.dev',
    status: 'online',
    ssl: false,
    description: 'Real-time chat backend service',
    tags: ['development', 'public'],
    createdAt: Date.now() - 600000,
  },
  {
    id: 8,
    title: 'ChatApp Frontend',
    category: 'Dev',
    url: 'chatapp.novitech.dev',
    status: 'online',
    ssl: false,
    description: 'Chat application web interface',
    tags: ['development', 'public'],
    createdAt: Date.now() - 700000,
  },
  {
    id: 9,
    title: 'Iceberg CRM',
    category: 'Dev',
    url: 'id.iceberg-crm.internal.novitech.dev',
    status: 'online',
    ssl: true,
    description: 'Customer relationship management system',
    tags: ['production', 'internal'],
    createdAt: Date.now() - 800000,
  },
  {
    id: 10,
    title: 'Qoldai',
    category: 'Dev',
    url: 'qoldai.novitech.dev',
    status: 'online',
    ssl: false,
    description: 'Support and ticketing platform',
    tags: ['development', 'public'],
    createdAt: Date.now() - 900000,
  },
  {
    id: 11,
    title: 'TrueSearch',
    category: 'Dev',
    url: 'truesearch.novitech.dev',
    status: 'online',
    ssl: false,
    description: 'Full-text search engine',
    tags: ['development'],
    createdAt: Date.now() - 1000000,
  },
  {
    id: 12,
    title: 'CEO Dashboard',
    category: 'Dev',
    url: 'ceo.novitech.dev',
    status: 'online',
    ssl: false,
    description: 'Executive analytics dashboard',
    tags: ['production', 'internal'],
    createdAt: Date.now() - 1100000,
  },

  // Media & Personal
  {
    id: 13,
    title: 'Immich',
    category: 'Media',
    url: 'immich.internal.novitech.dev',
    status: 'online',
    ssl: true,
    description: 'Self-hosted photo and video backup',
    tags: ['internal'],
    createdAt: Date.now() - 1200000,
  },
  {
    id: 14,
    title: 'Jellyfin',
    category: 'Media',
    url: 'jellyfin.internal.novitech.dev',
    status: 'online',
    ssl: true,
    description: 'Media streaming server',
    tags: ['internal'],
    createdAt: Date.now() - 1300000,
  },
  {
    id: 15,
    title: 'Minecraft Server',
    category: 'Personal',
    url: 'play.novitech.dev',
    status: 'online',
    ssl: true,
    description: 'Game server for friends',
    tags: ['public'],
    createdAt: Date.now() - 1400000,
  },
  {
    id: 16,
    title: 'Birthday Project',
    category: 'Personal',
    url: 'iloveyou.novitech.dev',
    status: 'online',
    ssl: false,
    description: 'Special birthday surprise website',
    tags: ['public'],
    createdAt: Date.now() - 1500000,
  },
  {
    id: 17,
    title: 'Google Meet',
    category: 'Personal',
    url: 'meet.novitech.dev',
    status: 'online',
    ssl: true,
    description: 'Video conferencing redirect',
    tags: ['public'],
    createdAt: Date.now() - 1600000,
  },
  {
    id: 18,
    title: 'Earth App',
    category: 'Personal',
    url: 'earth.novitech.dev',
    status: 'online',
    ssl: false,
    description: 'Interactive earth visualization',
    tags: ['public', 'development'],
    createdAt: Date.now() - 1700000,
  },
  {
    id: 19,
    title: 'Fire Suppression',
    category: 'Personal',
    url: 'fire.novitech.dev',
    status: 'online',
    ssl: false,
    description: 'Emergency response system',
    tags: ['critical', 'internal'],
    createdAt: Date.now() - 1800000,
  },
]

export const SERVICES_LOCAL_STORAGE_KEY = 'novitech_services'
